name: Link Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: >
            --no-progress
            --exclude-mail
            --exclude-private
            --exclude 'vbg.de/pmt'
            --accept 200,204,301,302
            './src/pages/**/*.html'
          fail: true
